// Board
const BOARD_USERIDS_MAX_LENGTH = 100;
const BOARD_TAGIDS_MAX_LENGTH = 100;
const BOARD_COLUMNS_MAX_LENGTH = 20;
const BOARD_COLUMN_TASKS_MAX_LENGTH = 500;
const BOARD_COLUMN_TASK_TAGIDS_MAX_LENGTH = 100;
const BOARD_COLUMN_TASK_ASSIGNEEIDS_MAX_LENGTH = 10;
